---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  instance_id: i-cfb086da
  image_type: m3.medium
  image_id: ami-0276a81f
  security_groups:
  - default
  - web
  external_host: ec2-54-94-239-250.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.239.250
  internal_host: ip-172-31-31-195.sa-east-1.compute.internal
  internal_ip: 172.31.31.195
  zone: sa-east-1a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.94.239.250
- !ruby/object:Rubber::Configuration::InstanceItem
  name: jobs
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: background_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sidekiq
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  instance_id: i-47b18752
  image_type: m3.medium
  image_id: ami-0276a81f
  security_groups:
  - default
  external_host: ec2-54-94-218-68.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.218.68
  internal_host: ip-172-31-19-155.sa-east-1.compute.internal
  internal_ip: 172.31.19.155
  zone: sa-east-1a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.94.218.68
- volumes: {}
  static_ips:
    app01: 54.94.239.250
    jobs: 54.94.218.68
