---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-4e6f585b
  image_type: t2.micro
  image_id: ami-af9925b2
  security_groups:
  - default
  external_host: ec2-54-94-250-210.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.250.210
  internal_host: ip-172-31-21-201.sa-east-1.compute.internal
  internal_ip: 172.31.21.201
  zone: sa-east-1
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.94.250.210
- !ruby/object:Rubber::Configuration::InstanceItem
  name: jobs
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: background_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sidekiq
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-4e6f585b
  image_type: t2.micro
  image_id: ami-af9925b2
  security_groups:
  - default
  external_host: ec2-54-94-250-210.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.250.210
  internal_host: ip-172-31-21-201.sa-east-1.compute.internal
  internal_ip: 172.31.21.201
  zone: sa-east-1
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.94.250.210
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-4e6f585b
  image_type: t2.micro
  image_id: ami-af9925b2
  security_groups:
  - default
  external_host: ec2-54-94-250-210.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.250.210
  internal_host: ip-172-31-21-201.sa-east-1.compute.internal
  internal_ip: 172.31.21.201
  zone: sa-east-1
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.94.250.210
- !ruby/object:Rubber::Configuration::InstanceItem
  name: aircrm
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-4e6f585b
  image_type: t2.micro
  image_id: ami-af9925b2
  security_groups:
  - default
  - web
  external_host: ec2-54-94-250-210.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.250.210
  internal_host: ip-172-31-21-201.sa-east-1.compute.internal
  internal_ip: 172.31.21.201
  zone: sa-east-1
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips:
    web01: 54.94.250.210
    db01: 54.94.250.210
    jobs: 54.94.250.210
    app01: 54.94.250.210











