---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-684d7f60
  image_type: c1.medium
  image_id: ami-fe1973ce
  security_groups:
  - default
  external_host: ec2-50-112-131-216.us-west-2.compute.amazonaws.com
  external_ip: 50.112.131.216
  internal_host: ip-172-31-5-124.us-west-2.compute.internal
  internal_ip: 172.31.5.124
  zone: us-west-2c
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 50.112.131.216
- !ruby/object:Rubber::Configuration::InstanceItem
  name: jobs
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: background_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sidekiq
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-06ad2c0b
  image_type: m2.xlarge
  image_id: ami-fe1973ce
  security_groups:
  - default
  external_host: ec2-54-187-185-20.us-west-2.compute.amazonaws.com
  external_ip: 54.187.185.20
  internal_host: ip-172-31-26-208.us-west-2.compute.internal
  internal_ip: 172.31.26.208
  zone: us-west-2a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.187.185.20
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-f32dacfe
  image_type: m2.xlarge
  image_id: ami-fe1973ce
  security_groups:
  - default
  external_host: ec2-54-187-87-93.us-west-2.compute.amazonaws.com
  external_ip: 54.187.87.93
  internal_host: ip-172-31-16-142.us-west-2.compute.internal
  internal_ip: 172.31.16.142
  zone: us-west-2a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.187.87.93
- volumes: {}
  static_ips:
    web01: 54.186.41.158
    db01: 50.112.131.216
    jobs: 54.187.185.20
    app01: 54.187.87.93
