---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: aircrm.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-15142200
  image_type: t1.micro
  image_id: ami-0276a81f
  security_groups:
  - default
  - web
  external_host: ec2-54-94-239-250.sa-east-1.compute.amazonaws.com
  external_ip: 54.94.239.250
  internal_host: ip-172-31-22-111.sa-east-1.compute.internal
  internal_ip: 172.31.22.111
  zone: sa-east-1a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.94.239.250
- volumes: {}
  static_ips:
    app01: 54.94.239.250
