# OPTIONAL: The dns provider to use.  Need to exist in dns_providers below
# dns_provider: nettica

# OPTIONAL: The configuration for each dns provider (nettica|zerigo|dyndns)
#          This lets rubber update a dynamic dns service with the instance alias and ip
#
dns_providers:
  aws:
    access_key: "#{cloud_providers.aws.access_key}"
    access_secret: "#{cloud_providers.aws.secret_access_key}"
    type: A
    ttl: 300
